trigger: 
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'omyorgapps'
  EnvironmentType: 'nonprod'
  ResourceGroupName: 'ToyWebsite'
  DeploymentDefaultLocation: 'canadacentral'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deployToyManualsStorageAccount $(DeployToyManualsStorageAccount)