
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

variables:
- group: github-mirror-secrets
- name: bicepFile
  value: "bicep/main.bicep"
- name: location
  value: "canadacentral"
- name: resourceGroup
  value: "rg-whatif-lz-portfolio"
- name: env
  value: "dev"
- name: workloadName
  value: "portfolio"
- name: monitoringEnabled
  value: "false"
- name: storageEnabled
  value: "false"
- name: GITHUB_OWNER
  value: "osvaldoy"
- name: GITHUB_REPO
  value: "azure-landing-zone-bicep"


stages:
- stage: Validate
  displayName: "Validate (Bicep build)"
  jobs:
  - job: Build
    displayName: "Bicep build"
    pool:
      vmImage: "windows-latest"
    steps:
    - checkout: self
    - template: templates/validate.yml
      parameters:
        bicepFile: $(bicepFile)

- stage: WhatIf
  displayName: "What-If (no deploy)"
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: WhatIf
    displayName: "ARM What-If"
    pool:
      vmImage: "windows-latest"
    steps:
    - checkout: self
    - template: templates/whatif.yml
      parameters:
        bicepFile: $(bicepFile)
        location: $(location)
        resourceGroup: $(resourceGroup)
        workloadName: $(workloadName)
        env: $(env)
        monitoringEnabled: $(monitoringEnabled)
        storageEnabled: $(storageEnabled)
- stage: MirrorGitHub
  displayName: "Mirror to GitHub (read-only)"
  dependsOn:
    - Validate
    - WhatIf
  condition: >
    and(
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/main')
    )
  jobs:
    - job: Mirror
      displayName: "Push Azure Repos -> GitHub"
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
          persistCredentials: true
          fetchDepth: 0

        - bash: |
            set -euo pipefail

            git config user.email "azuredevops-bot@local"
            git config user.name  "azuredevops-bot"

            git fetch origin --prune --tags

            if ! git remote get-url github >/dev/null 2>&1; then
              git remote add github "https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git"
            fi

            AUTH_HEADER=$(printf "Authorization: token %s" "$GITHUB_PAT")

            git -c http.extraheader="$AUTH_HEADER" push github HEAD:main
            git -c http.extraheader="$AUTH_HEADER" push github --tags

            echo "Mirror completed successfully."
          displayName: "Mirror main + tags to GitHub"
          env:
            GITHUB_PAT: $(GITHUB_PAT)
            GITHUB_OWNER: $(GITHUB_OWNER)
            GITHUB_REPO: $(GITHUB_REPO)
